// lib/config/instruments.js
export const INSTRUMENTS = [
  "EUR_USD",
  "AUD_USD",
  "GBP_USD",
  "USD_JPY",
  "EUR_JPY",
  "AUD_CAD",
  "AUD_CHF",
  "AUD_HKD",
  "AUD_JPY",
  "AUD_NZD",
  "AUD_SGD",
  "CAD_CHF",
  "CAD_HKD",
  "CAD_JPY",
  "CAD_SGD",
  "CHF_HKD",
  "CHF_JPY",
  "CHF_ZAR",
  "EUR_AUD",
  "EUR_CAD",
  "EUR_CHF",
  "EUR_CZK",
  "EUR_DKK",
  "EUR_GBP",
  "EUR_HKD",
  "EUR_HUF",
  "EUR_NOK",
  "EUR_NZD",
  "EUR_PLN",
  "EUR_SEK",
  "EUR_SGD",
  "EUR_TRY",
  "EUR_ZAR",
  "GBP_AUD",
  "NZD_SGD",
  "NZD_USD",
  "SGD_CHF",
  "SGD_JPY",
  "TRY_JPY",
  "USD_CAD",
  "USD_CHF",
  "USD_CNH",
  "USD_CZK",
  "USD_DKK",
  "USD_HKD",
  "USD_HUF",
  "USD_MXN",
  "USD_NOK",
  "USD_PLN",
  "USD_SEK",
  "USD_SGD",
  "USD_THB",
  "USD_TRY",
  "USD_ZAR",
  "ZAR_JPY",
];

export const EXCLUDE_INSTRUMENTS = ["TRY_JPY", "USD_ZAR"];

export const TRADING_PARAMS = {
  RSI_PERIOD: 14,
  RSI_OVERBOUGHT: 65,
  RSI_OVERSOLD: 35,
  SMA_PERIOD: 200,
  ATR_PERIOD: 14,
  MIN_ATR_THRESHOLD: 0.0005,
  STOP_LOSS_PIPS: 50, // Adjust to 5000 if needed
  TAKE_PROFIT_PIPS: 100,
  RISK_PERCENT: 0.02,
  MAX_SPREAD: {
    majors: 0.0005,
    crosses: 0.001,
    exotics: 0.02,
  },
};
